apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhythm-archive

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: rhythm-archive
  version: v1.0.0

images:
  - name: rhythm-archive
    newTag: latest
